export const ADD_ALL_PLAYERS_ACTION = 'ADD_ALL_PLAYERS_ACTION';
export const CLEAR_ALL_PLAYERS_ACTION = 'CLEAR_ALL_PLAYERS_ACTION';
export const ADD_PLAYER_ACTION = 'ADD_PLAYER_ACTION';
export const CHANGE_PLAYER_ACTION = 'CHANGE_PLAYER_ACTION';
export const REMOVE_PLAYER_ACTION = 'REMOVE_PLAYER_ACTION';

export const LOAD_PLAYERS_FINISHED_ACTION = 'LOAD_PLAYERS_FINISHED_ACTION';
export const CHANGE_SEARCH_FIELD_PLAYERS_ACTION = 'CHANGE_SEARCH_FIELD_PLAYERS_ACTION';

