export const ADD_ALL_MY_REGISTRATIONS_ACTION = 'ADD_ALL_MY_REGISTRATIONS_ACTION';
export const CLEAR_ALL_MY_REGISTRATIONS_ACTION = 'CLEAR_ALL_MY_REGISTRATIONS_ACTION';
export const ADD_MY_REGISTRATION_ACTION = 'ADD_MY_REGISTRATION_ACTION';
export const CHANGE_MY_REGISTRATION_ACTION = 'CHANGE_MY_REGISTRATION_ACTION';
export const REMOVE_MY_REGISTRATION_ACTION = 'REMOVE_MY_REGISTRATION_ACTION';

export const LOAD_MY_REGISTRATIONS_FINISHED_ACTION = 'LOAD_MY_REGISTRATIONS_FINISHED_ACTION';

