export const ADD_ALL_MY_TOURNAMENTS_ACTION = 'ADD_ALL_MY_TOURNAMENTS_ACTION';
export const CLEAR_ALL_MY_TOURNAMENTS_ACTION = 'CLEAR_ALL_MY_TOURNAMENTS_ACTION';
export const ADD_MY_TOURNAMENT_ACTION = 'ADD_MY_TOURNAMENT_ACTION';
export const CHANGE_MY_TOURNAMENT_ACTION = 'CHANGE_MY_TOURNAMENT_ACTION';
export const REMOVE_MY_TOURNAMENT_ACTION = 'REMOVE_MY_TOURNAMENT_ACTION';

export const LOAD_MY_TOURNAMENTS_FINISHED_ACTION = 'LOAD_MY_TOURNAMENTS_FINISHED_ACTION';

