export const ADD_ALL_TOURNAMENTS_ACTION = 'ADD_ALL_TOURNAMENTS_ACTION';
export const CLEAR_ALL_TOURNAMENTS_ACTION = 'CLEAR_ALL_TOURNAMENTS_ACTION';
export const ADD_TOURNAMENT_ACTION = 'ADD_TOURNAMENT_ACTION';
export const CHANGE_TOURNAMENT_ACTION = 'CHANGE_TOURNAMENT_ACTION';
export const REMOVE_TOURNAMENT_ACTION = 'REMOVE_TOURNAMENT_ACTION';

export const LOAD_TOURNAMENTS_FINISHED_ACTION = 'LOAD_TOURNAMENTS_FINISHED_ACTION';

export const CHANGE_FILTER_TOURNAMENTS_ACTION = 'CHANGE_FILTER_TOURNAMENTS_ACTION';
export const CHANGE_SEARCH_FIELD_TOURNAMENTS_ACTION = 'CHANGE_SEARCH_FIELD_TOURNAMENTS_ACTION';
