export const ADD_GAME_ACTION = 'ADD_GAME_ACTION';
export const ADD_TO_FILTER_GAME_ACTION = 'ADD_TO_FILTER_GAME_ACTION';
export const CLEAR_GAMES_ACTION = 'CLEAR_GAMES_ACTION';
export const ADD_ALL_GAMES_ACTION = 'ADD_ALL_GAMES_ACTION';

export const LOAD_GAMES_FINISHED_ACTION = 'LOAD_GAMES_FINISHED_ACTION';
