import {Action} from '@ngrx/store';
import {Registration} from '../../../../shared/model/registration';
import {RegistrationPush} from '../../../../shared/dto/registration-push';
import {TournamentPlayer} from '../../../../shared/model/tournament-player';
import {ArmyListTournamentPlayerPush} from '../../../../shared/dto/armyList-tournamentPlayer-push';
import {ArmyList} from '../../../../shared/model/armyList';
import {TournamentManagementConfiguration} from '../../../../shared/dto/tournament-management-configuration';
import {ScenarioSelectedModel} from '../../../../shared/dto/scenario-selected-model';
import {GameResult} from '../../../../shared/dto/game-result';
import {SwapGames} from '../../../../shared/dto/swap-player';
import {DropPlayerPush} from '../../../../shared/dto/drop-player-push';
import {TournamentRanking} from '../../../../shared/model/tournament-ranking';
import {PublishRound} from '../../../../shared/dto/publish-round';
import {PlayerRegistrationChange} from '../../../../shared/dto/playerRegistration-change';
import {ArmyListRegistrationPush} from '../../../../shared/dto/armyList-registration-push';

export const SET_ACTUAL_TOURNAMENT_ACTION = 'SET_ACTUAL_TOURNAMENT_ACTION';
export const UNSET_ACTUAL_TOURNAMENT_ACTION = 'UNSET_ACTUAL_TOURNAMENT_ACTION';

export const ADD_ACTUAL_TOURNAMENT_REGISTRATION_ACTION = 'ADD_ACTUAL_TOURNAMENT_REGISTRATION_ACTION';
export const CHANGE_ACTUAL_TOURNAMENT_REGISTRATION_ACTION = 'CHANGE_ACTUAL_TOURNAMENT_REGISTRATION_ACTION';
export const REMOVE_ACTUAL_TOURNAMENT_REGISTRATION_ACTION = 'REMOVE_ACTUAL_TOURNAMENT_REGISTRATION_ACTION';
export const CLEAR_ACTUAL_TOURNAMENT_REGISTRATIONS_ACTION = 'CLEAR_ACTUAL_TOURNAMENT_REGISTRATIONS_ACTION';
export const ADD_ALL_ACTUAL_TOURNAMENT_REGISTRATIONS_ACTION = 'ADD_ALL_ACTUAL_TOURNAMENT_REGISTRATION_ACTION';
export const LOAD_REGISTRATIONS_FINISHED_ACTION = 'LOAD_REGISTRATIONS_FINISHED_ACTION';

export const ADD_ACTUAL_TOURNAMENT_PLAYER_ACTION = 'ADD_ACTUAL_TOURNAMENT_PLAYER_ACTION';
export const CHANGE_ACTUAL_TOURNAMENT_PLAYER_ACTION = 'CHANGE_ACTUAL_TOURNAMENT_PLAYER_ACTION';
export const REMOVE_ACTUAL_TOURNAMENT_PLAYER_ACTION = 'REMOVE_ACTUAL_TOURNAMENT_PLAYER_ACTION';
export const CLEAR_ACTUAL_TOURNAMENT_PLAYERS_ACTION = 'CLEAR_ACTUAL_TOURNAMENT_PLAYERS_ACTION';
export const ADD_ALL_ACTUAL_TOURNAMENT_PLAYERS_ACTION = 'ADD_ALL_ACTUAL_TOURNAMENT_PLAYER_ACTION';
export const LOAD_TOURNAMENT_PLAYERS_FINISHED_ACTION = 'LOAD_TOURNAMENT_PLAYERS_FINISHED_ACTION';
export const CHANGE_SEARCH_FIELD_TOURNAMENT_PLAYERS_ACTION = 'CHANGE_SEARCH_FIELD_TOURNAMENT_PLAYERS_ACTION';

export const ADD_ACTUAL_TOURNAMENT_ARMY_LIST_ACTION = 'ADD_ACTUAL_TOURNAMENT_ARMY_LIST_ACTION';
export const CHANGE_ACTUAL_TOURNAMENT_ARMY_LIST_ACTION = 'CHANGE_ACTUAL_TOURNAMENT_ARMY_LIST_ACTION';
export const REMOVE_ACTUAL_TOURNAMENT_ARMY_LIST_ACTION = 'REMOVE_ACTUAL_TOURNAMENT_ARMY_LIST_ACTION';
export const CLEAR_ACTUAL_TOURNAMENT_ARMY_LISTS_ACTION = 'CLEAR_ACTUAL_TOURNAMENT_ARMY_LISTS_ACTION';
export const ADD_ALL_ACTUAL_TOURNAMENT_ARMY_LISTS_ACTION = 'ADD_ALL_ACTUAL_TOURNAMENT_ARMY_LIST_ACTION';

export const ADD_ACTUAL_TOURNAMENT_RANKING_ACTION = 'ADD_ACTUAL_TOURNAMENT_RANKING_ACTION';
export const CHANGE_ACTUAL_TOURNAMENT_RANKING_ACTION = 'CHANGE_ACTUAL_TOURNAMENT_RANKING_ACTION';
export const REMOVE_ACTUAL_TOURNAMENT_RANKING_ACTION = 'REMOVE_ACTUAL_TOURNAMENT_RANKING_ACTION';
export const CLEAR_ACTUAL_TOURNAMENT_RANKINGS_ACTION = 'CLEAR_ACTUAL_TOURNAMENT_RANKINGS_ACTION';
export const ADD_ALL_ACTUAL_TOURNAMENT_RANKINGS_ACTION = 'ADD_ALL_ACTUAL_TOURNAMENT_RANKING_ACTION';
export const LOAD_TOURNAMENT_RANKINGS_FINISHED_ACTION = 'LOAD_TOURNAMENT_RANKINGS_FINISHED_ACTION';

export const ADD_ACTUAL_TOURNAMENT_GAME_ACTION = 'ADD_ACTUAL_TOURNAMENT_GAME_ACTION';
export const CHANGE_ACTUAL_TOURNAMENT_GAME_ACTION = 'CHANGE_ACTUAL_TOURNAMENT_GAME_ACTION';
export const REMOVE_ACTUAL_TOURNAMENT_GAME_ACTION = 'REMOVE_ACTUAL_TOURNAMENT_GAME_ACTION';
export const CLEAR_ACTUAL_TOURNAMENT_GAMES_ACTION = 'CLEAR_ACTUAL_TOURNAMENT_GAMES_ACTION';
export const ADD_ALL_ACTUAL_TOURNAMENT_GAMES_ACTION = 'ADD_ALL_ACTUAL_TOURNAMENT_GAME_ACTION';
export const LOAD_TOURNAMENT_GAMES_FINISHED_ACTION = 'LOAD_TOURNAMENT_GAMES_FINISHED_ACTION';
export const CHANGE_SEARCH_FIELD_GAMES_ACTION = 'CHANGE_SEARCH_FIELD_GAMES_ACTION';
export const CHANGE_SCENARIO_ACTION = 'CHANGE_SCENARIO_ACTION';
export const SHOW_ONLY_MY_GAME_ACTION = 'SHOW_ONLY_MY_GAME_ACTION';

export const ADD_ACTUAL_TOURNAMENT_TEAM_REGISTRATION_ACTION = 'ADD_ACTUAL_TOURNAMENT_TEAM_REGISTRATION_ACTION';
export const CHANGE_ACTUAL_TOURNAMENT_TEAM_REGISTRATION_ACTION = 'CHANGE_ACTUAL_TOURNAMENT_TEAM_REGISTRATION_ACTION';
export const REMOVE_ACTUAL_TOURNAMENT_TEAM_REGISTRATION_ACTION = 'REMOVE_ACTUAL_TOURNAMENT_TEAM_REGISTRATION_ACTION';
export const CLEAR_ACTUAL_TOURNAMENT_TEAM_REGISTRATIONS_ACTION = 'CLEAR_ACTUAL_TOURNAMENT_TEAM_REGISTRATIONS_ACTION';
export const ADD_ALL_ACTUAL_TOURNAMENT_TEAM_REGISTRATIONS_ACTION = 'ADD_ALL_ACTUAL_TOURNAMENT_TEAM_REGISTRATION_ACTION';
export const LOAD_TEAM_REGISTRATIONS_FINISHED_ACTION = 'LOAD_TEAM_REGISTRATIONS_FINISHED_ACTION';

export const ADD_ACTUAL_TOURNAMENT_TEAM_ACTION = 'ADD_ACTUAL_TOURNAMENT_TEAMS_ACTION';
export const CHANGE_ACTUAL_TOURNAMENT_TEAM_ACTION = 'CHANGE_ACTUAL_TOURNAMENT_TEAMS_ACTION';
export const REMOVE_ACTUAL_TOURNAMENT_TEAM_ACTION = 'REMOVE_ACTUAL_TOURNAMENT_TEAMS_ACTION';
export const CLEAR_ACTUAL_TOURNAMENT_TEAMS_ACTION = 'CLEAR_ACTUAL_TOURNAMENT_TEAMS_ACTION';
export const ADD_ALL_ACTUAL_TOURNAMENT_TEAMS_ACTION = 'ADD_ALL_ACTUAL_TOURNAMENT_TEAMS_ACTION';
export const LOAD_TEAMS_FINISHED_ACTION = 'LOAD_TEAMS_FINISHED_ACTION';
export const CHANGE_SEARCH_FIELD_TOURNAMENT_TEAMS_ACTION = 'CHANGE_SEARCH_FIELD_TOURNAMENT_TEAMS_ACTION';


export const ADD_ACTUAL_TOURNAMENT_TEAM_GAME_ACTION = 'ADD_ACTUAL_TOURNAMENT_TEAM_GAME_ACTION';
export const CHANGE_ACTUAL_TOURNAMENT_TEAM_GAME_ACTION = 'CHANGE_ACTUAL_TOURNAMENT_TEAM_GAME_ACTION';
export const REMOVE_ACTUAL_TOURNAMENT_TEAM_GAME_ACTION = 'REMOVE_ACTUAL_TOURNAMENT_TEAM_GAME_ACTION';
export const CLEAR_ACTUAL_TOURNAMENT_TEAM_GAMES_ACTION = 'CLEAR_ACTUAL_TOURNAMENT_TEAM_GAMES_ACTION';
export const ADD_ALL_ACTUAL_TOURNAMENT_TEAM_GAMES_ACTION = 'ADD_ALL_ACTUAL_TOURNAMENT_TEAM_GAME_ACTION';
export const LOAD_TOURNAMENT_TEAM_GAMES_FINISHED_ACTION = 'LOAD_TOURNAMENT_TEAM_GAMES_FINISHED_ACTION';
export const CHANGE_SEARCH_FIELD_TEAM_GAMES_ACTION = 'CHANGE_SEARCH_FIELD_TEAM_GAMES_ACTION';

export const SHOW_ONLY_MY_TEAM_GAME_ACTION = 'SHOW_ONLY_MY_TEAM_GAME_ACTION';

export const ADD_ACTUAL_TOURNAMENT_TEAM_RANKING_ACTION = 'ADD_ACTUAL_TOURNAMENT_TEAM_RANKING_ACTION';
export const CHANGE_ACTUAL_TOURNAMENT_TEAM_RANKING_ACTION = 'CHANGE_ACTUAL_TOURNAMENT_TEAM_RANKING_ACTION';
export const REMOVE_ACTUAL_TOURNAMENT_TEAM_RANKING_ACTION = 'REMOVE_ACTUAL_TOURNAMENT_TEAM_RANKING_ACTION';
export const CLEAR_ACTUAL_TOURNAMENT_TEAM_RANKINGS_ACTION = 'CLEAR_ACTUAL_TOURNAMENT_TEAM_RANKINGS_ACTION';
export const ADD_ALL_ACTUAL_TOURNAMENT_TEAM_RANKINGS_ACTION = 'ADD_ALL_ACTUAL_TOURNAMENT_TEAM_RANKING_ACTION';
export const LOAD_TOURNAMENT_TEAM_RANKINGS_FINISHED_ACTION = 'LOAD_TOURNAMENT_TEAM_RANKINGS_FINISHED_ACTION';

