export const ADD_ALL_MY_GAMES_ACTION = 'ADD_ALL_MY_GAMES_ACTION';
export const CLEAR_ALL_MY_GAMES_ACTION = 'CLEAR_ALL_MY_GAMES_ACTION';
export const ADD_MY_GAME_ACTION = 'ADD_MY_GAME_ACTION';
export const CHANGE_MY_GAME_ACTION = 'CHANGE_MY_GAME_ACTION';
export const REMOVE_MY_GAME_ACTION = 'REMOVE_MY_GAME_ACTION';

export const LOAD_MY_GAMES_FINISHED_ACTION = 'LOAD_MY_GAMES_FINISHED_ACTION';

